"""
Generated by /generate-pytest from FISTesting/dsl/examples/PAM-USD-MULTICOVER-001/steps.yaml.
Do not edit by hand — re-run the prompt to regenerate.
"""
# Generated by GitHub Copilot
import json
import re
import uuid
from pathlib import Path

import httpx
import pytest
from playwright.sync_api import expect

from runner.context import context, reset_context, get as ctx_get, set as ctx_set

base_url = "http://127.0.0.1:8181"  # mock runtime


def test_pam_usd_multicover_001(page, subtests):
    """Execute PAM-USD-MULTICOVER-001 generated steps against the mock runtime."""
    reset_context()

    # ── Step 1 — inject_payment + assert_http_status  (verifies: [shared.R1]) ──
    with subtests.test(msg="Step 1 — inject_payment + assert_http_status (verifies shared.R1)"):
        params = {
            "payload_ref": "FISTesting/payloads/pain001_base.json",
            "overrides": {
                "creditTransferTransaction.currency": "EUR",
                "creditTransferTransaction.amount": "6000.00",
                "controlSum": "5000.00",
                "cashfitMetadata.routingPattern": "multiple_cover",
            },
            "omit": [
                "creditTransferTransaction.remittanceInformation",
                "paymentInformation.categoryPurpose",
            ],
        }

        # verifies: [shared.R1]
        # --- skill: inject_payment ---
        import json
        import uuid
        from pathlib import Path
        import httpx
        from runner.context import set as ctx_set

        def _set_path(obj, dotted_path, value):
            keys = dotted_path.split(".")
            cur = obj
            for k in keys[:-1]:
                if not isinstance(cur.get(k), dict):
                    cur[k] = {}
                cur = cur[k]
            cur[keys[-1]] = value

        def _del_path(obj, dotted_path):
            keys = dotted_path.split(".")
            cur = obj
            for k in keys[:-1]:
                if  isinstance(cur.get(k), dict):
                    return
                cur = cur[k]
            cur.pop(keys[-1], None)

        with open(Path(params["payload_ref"])) as f:
            payload = json.load(f)

        unique = uuid.uuid4().hex[:12]
        unique_uetr = str(uuid.uuid4())
        payload_str = json.dumps(payload)
        payload_str = payload_str.replace("${unique_id}", unique)
        payload_str = payload_str.replace("${unique_uetr}", unique_uetr)
        payload = json.loads(payload_str)

        for path, value in (params.get("overrides") or {}).items():
            _set_path(payload, path, value)
        for path in (params.get("omit") or []):
            _del_path(payload, path)

        resp = httpx.post(f"{base_url}/tests", json=payload, timeout=5.0)
        ctx_set("last_response", resp)
        ctx_set("message_id", payload.get("messageId"))
        if 200 <= resp.status_code < 300:
            body = resp.json()
            ctx_set("payment_id", body["id"])
            ctx_set("reference", body["reference"])
        assertion_target = resp

        params = {"expected": 202}
        # --- skill: assert_http_status ---
        from runner.context import get as ctx_get

        response = assertion_target if "assertion_target" in dir() else ctx_get("last_response")
        expected = int(params["expected"])
        assert response is not None, "no response in scope to assert against"
        assert response.status_code == expected, (
            f"expected HTTP {expected}, got {response.status_code}: {response.text[:200]}"
        )

    # ── Step 2 — wait_for_payment_status + assert_payment_status_in  (verifies: [shared.R2]) ──
    with subtests.test(msg="Step 2 — wait_for_payment_status + assert_payment_status_in (verifies shared.R2)"):
        params = {
            "allowed": ["PENDING_"],
            "timeout": 30.0,
        }

        # verifies: [shared.R2]
        # --- skill: wait_for_payment_status ---
        import time
        import httpx
        from runner.context import get as ctx_get

        payment_id = ctx_get("payment_id")
        allowed = set(params["allowed"])
        timeout = float(params.get("timeout", 30.0))
        poll_interval = float(params.get("poll_interval", 0.5))

        deadline = time.monotonic() + timeout
        last_status = None
        matched = None
        while time.monotonic() < deadline:
            resp = httpx.get(f"{base_url}/payments/{payment_id}", timeout=5.0)
            resp.raise_for_status()
            payment = resp.json()
            last_status = payment.get("status")
            if last_status in allowed:
                matched = payment
                break
            time.sleep(poll_interval)

        if matched is None:
            raise AssertionError(
                f"payment {payment_id!r} did not reach any of {sorted(allowed)!r} "
                f"within {timeout}s - last status seen: {last_status!r}"
            )

        assertion_target = matched

        params = {"allowed": ["RECEIVED", "VALIDATED", "ENRICHED", "PENDING_SUBMISSION"]}
        # --- skill: assert_payment_in ---
        allowed = set(params["allowed"])
        assert isinstance(assertion_target, dict), (
            f"expected a dict from preceding action, got {type(assertion_target).__name__}"
        )
        actual = assertion_target.get("status")
        assert actual is not None, "preceding action did not produce a 'status' field"
        assert actual in allowed, (
            f"status {actual!r} not in allowed set {sorted(allowed)!r}"
        )

    # ── Step 3 — search_payment_kafka + assert_payment_status_in  (verifies: [shared.R2]) ──
    with subtests.test(msg="Step 3 — search_payment_kafka + assert_payment_status_in (verifies shared.R2)"):
        params = {}

        # verifies: [shared.R2]
        # --- skill: search_payment_kafka ---
        import httpx
        from runner.context import get as ctx_get

        payment_id = ctx_get("payment_id")
        resp = httpx.get(f"{base_url}/__mock__/kafka/fis.business.events", timeout=5.0)
        resp.raise_for_status()
        events = resp.json()
        matching = [e for e in events if e["value"].get("payment_id") == payment_id]
        assert matching, f"no business event found for payment_id {payment_id!r}"
        latest = matching[-1]
        assertion_target = {
            "status": latest["value"]["to_status"],
            "ts": latest["value"]["ts"],
        }

        params = {"allowed": ["RECEIVED", "VALIDATED", "ENRICHED", "PENDING_SUBMISSION"]}
        # --- skill: assert_payment_status_in ---
        allowed = set(params["allowed"])
        assert isinstance(assertion_target, dict), (
            f"expected a dict from preceding action, got {type(assertion_target).__name__}"
        )
        actual = assertion_target.get("status")
        assert actual is not None, "preceding action did not produce a 'status' field"
        assert actual in allowed, (
            f"status {actual!r} not in allowed set {sorted(allowed)!r}"
        )

    # ── Step 4 — search_payment_ui + assert_ui_payment_status_in  (verifies: [shared.R2]) ──
    with subtests.test(msg="Step 4 — search_payment_ui + assert_ui_payment_status_in (verifies shared.R2)"):
        params = {}

        # verifies: [shared.R2]
        # --- skill: search_payment_ui ---
        from runner.context import get as ctx_get

        payment_id = ctx_get("payment_id")
        page.goto(f"{base_url}/payments-ui/{payment_id}")

        params = {"allowed": ["RECEIVED", "VALIDATED", "ENRICHED", "PENDING_SUBMISSION"]}
        # --- skill: assert_ui_payment_status_in ---
        import re
        from playwright.sync_api import expect

        allowed = params["allowed"]
        assert allowed, "allowed status set must not be empty"
        pattern = "|".join(re.escape(s) for s in allowed)
        expect(
            page.locator("[data-testid='payment-status']")
        ).to_have_text(re.compile(rf"^\s*({pattern})\s*$"), timeout=5000)

    # ── Step 5 — submit_to_csm + assert_http_status  (verifies: [shared.R3]) ──
    with subtests.test(msg="Step 5 — submit_to_csm + assert_http_status (verifies shared.R3)"):
        params = {}

        # verifies: [shared.R3]
        # --- skill: submit_to_csm ---
        import httpx
        from runner.context import get as ctx_get, set as ctx_set

        payment_id = ctx_get("payment_id")
        resp = httpx.post(
            f"{base_url}/payments/{payment_id}/submit-to-csm", timeout=5.0
        )
        ctx_set("last_response", resp)
        assertion_target = resp

        params = {"expected": 202}
        # --- skill: assert_http_status ---
        from runner.context import get as ctx_get

        response = assertion_target if "assertion_target" in dir() else ctx_get("last_response")
        expected = int(params["expected"])
        assert response is not None, "no response in scope to assert against"
        assert response.status_code == expected, (
            f"expected HTTP {expected}, got {response.status_code}: {response.text[:200]}"
        )

    # ── Step 6 — wait_for_payment_status + assert_payment_status_in  (verifies: [shared.R4]) ──
    with subtests.test(msg="Step 6 — wait_for_payment_status + assert_payment_status_in (verifies shared.R4)"):
        params = {
            "allowed": ["PACS008_EMITTED", "POSTED", "ACKNOWLEDGED", "SETTLED"],
            "timeout": 30.0,
        }

        # verifies: [shared.R4]
        # --- skill: wait_for_payment_status ---
        import time
        import httpx
        from runner.context import get as ctx_get

        payment_id = ctx_get("payment_id")
        allowed = set(params["allowed"])
        timeout = float(params.get("timeout", 30.0))
        poll_interval = float(params.get("poll_interval", 0.5))

        deadline = time.monotonic() + timeout
        last_status = None
        matched = None
        while time.monotonic() < deadline:
            resp = httpx.get(f"{base_url}/payments/{payment_id}", timeout=5.0)
            resp.raise_for_status()
            payment = resp.json()
            last_status = payment.get("status")
            if last_status in allowed:
                matched = payment
                break
            time.sleep(poll_interval)

        if matched is None:
            raise AssertionError(
                f"payment {payment_id!r} did not reach any of {sorted(allowed)!r} "
                f"within {timeout}s - last status seen: {last_status!r}"
            )

        assertion_target = matched

        params = {"allowed": ["PACS008_EMITTED", "POSTED", "ACKNOWLEDGED", "SETTLED"]}
        # --- skill: assert_payment_status_in ---
        allowed = set(params["allowed"])
        assert isinstance(assertion_target, dict), (
            f"expected a dict from preceding action, got {type(assertion_target).__name__}"
        )
        actual = assertion_target.get("status")
        assert actual is not None, "preceding action did not produce a 'status' field"
        assert actual in allowed, (
            f"status {actual!r} not in allowed set {sorted(allowed)!r}"
        )

    # ── Step 7 — wait_for_payment_status + assert_payment_status_in  (verifies: [shared.R5, shared.R6]) ──
    with subtests.test(msg="Step 7 — wait_for_payment_status + assert_payment_status_in (verifies shared.R5, shared.R6)"):
        params = {
            "allowed": ["SETTLED"],
            "timeout": 60.0,
        }

        # verifies: [shared.R5, shared.R6]
        # --- skill: wait_for_payment_status ---
        import time
        import httpx
        from runner.context import get as ctx_get

        payment_id = ctx_get("payment_id")
        allowed = set(params["allowed"])
        timeout = float(params.get("timeout", 30.0))
        poll_interval = float(params.get("poll_interval", 0.5))

        deadline = time.monotonic() + timeout
        last_status = None
        matched = None
        while time.monotonic() < deadline:
            resp = httpx.get(f"{base_url}/payments/{payment_id}", timeout=5.0)
            resp.raise_for_status()
            payment = resp.json()
            last_status = payment.get("status")
            if last_status in allowed:
                matched = payment
                break
            time.sleep(poll_interval)

        if matched is None:
            raise AssertionError(
                f"payment {payment_id!r} did not reach any of {sorted(allowed)!r} "
                f"within {timeout}s - last status seen: {last_status!r}"
            )

        assertion_target = matched

        params = {"allowed": ["SETTLED"]}
        # --- skill: assert_payment_status_in ---
        allowed = set(params["allowed"])
        assert isinstance(assertion_target, dict), (
            f"expected a dict from preceding action, got {type(assertion_target).__name__}"
        )
        actual = assertion_target.get("status")
        assert actual is not None, "preceding action did not produce a 'status' field"
        assert actual in allowed, (
            f"status {actual!r} not in allowed set {sorted(allowed)!r}"
        )

    # ── Step 8 — search_payment_kafka + assert_payment_status_in  (verifies: [shared.R5]) ──
    with subtests.test(msg="Step 8 — search_payment_kafka + assert_payment_status_in (verifies shared.R5)"):
        params = {}

        # verifies: [shared.R5]
        # --- skill: search_payment_kafka ---
        import httpx
        from runner.context import get as ctx_get

        payment_id = ctx_get("payment_id")
        resp = httpx.get(f"{base_url}/__mock__/kafka/fis.business.events", timeout=5.0)
        resp.raise_for_status()
        events = resp.json()
        matching = [e for e in events if e["value"].get("payment_id") == payment_id]
        assert matching, f"no business event found for payment_id {payment_id!r}"
        latest = matching[-1]
        assertion_target = {
            "status": latest["value"]["to_status"],
            "from_status": latest["value"].get("from_status"),
            "ts": latest["value"]["ts"],
        }

        params = {"allowed": ["SETTLED"]}
        # --- skill: assert_payment_status_in ---
        allowed = set(params["allowed"])
        assert isinstance(assertion_target, dict), (
            f"expected a dict from preceding action, got {type(assertion_target).__name__}"
        )
        actual = assertion_target.get("status")
        assert actual is not None, "preceding action did not produce a 'status' field"
        assert actual in allowed, (
            f"status {actual!r} not in allowed set {sorted(allowed)!r}"
        )

    # ── Step 9 — search_payment_ui + assert_ui_payment_status_in  (verifies: [shared.R7]) ──
    with subtests.test(msg="Step 9 — search_payment_ui + assert_ui_payment_status_in (verifies shared.R7)"):
        params = {}

        # verifies: [shared.R7]
        # --- skill: search_payment_ui ---
        from runner.context import get as ctx_get

        payment_id = ctx_get("payment_id")
        page.goto(f"{base_url}/payments-ui/{payment_id}")

        params = {"allowed": ["SETTLED"]}
        # --- skill: assert_ui_payment_status_in ---
        import re
        from playwright.sync_api import expect

        allowed = params["allowed"]
        assert allowed, "allowed status set must not be empty"
        pattern = "|".join(re.escape(s) for s in allowed)
        expect(
            page.locator("[data-testid='payment-status']")
        ).to_have_text(re.compile(rf"^\s*({pattern})\s*$"), timeout=5000)
